"""rename department

Revision ID: bb0a0ab01d75
Revises: d8116be4e409
Create Date: 2024-10-04 04:16:33.207194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0a0ab01d75'
down_revision = 'd8116be4e409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments', 'department')
    # ### end Alembic commands ###
